### ISSUE TITLE
The recent update to simhelper and nixieTubes is broken.

### ISSUE THREAD

**Issue by credomane** [justarandomgeek/factorio-simhelper#2]
Looking at the code it seems that the if check here https://github.com/justarandomgeek/factorio-simhelper/blob/f3835c5743ca36d7f1db2cbbb16da2840005ec19/funccapture.lua#L64 is `true` when it shouldn't be and the call to defineGlobal then fails because the function is nil.

A quick look around and I can't figure out where `__debugAdapter` is coming from since I do NOT have https://mods.factorio.com/mod/debugadapter installed.

![image](https://user-images.githubusercontent.com/1283031/171900291-bff82b73-c00d-4043-bd63-ddb09977a257.png)

**Comment by justarandomgeek** [comment]
Works fine without debugger for me. What other mod are you using that is incorrectly using the `__DebugAdapter` api (by writing something to it)?

**Comment by credomane** [comment]
All of these mods are enabled and the latest version as of when I originally made this ticket 30 minutes ago.

<details>
  <summary>Long list of mods</summary>

aai-containers
aai-industry
aai-programmable-structures
aai-programmable-vehicles
aai-signal-transmission
aai-signals
aai-vehicles-chaingunner
aai-vehicles-flame-tank
aai-vehicles-flame-tumbler
aai-vehicles-hauler
aai-vehicles-laser-tank
aai-vehicles-miner
aai-vehicles-warden
aai-zones
alien-biomes
alien-biomes-hr-terrain
ArmouredBiters
AutoDeconstruct
Automatic_Train_Painter
AutoTrash
bobinserters
BottleneckLite
bullet-trails
Cannon_Spidertron
combat-mechanics-overhaul
Companion_Drones
copy-recipe-to-chest
DarkNight
Dectorio
discovery_tree
Enhanced_Map_Colors
EpicArtillerySounds
even-distribution
EvoGUI
extended-descriptions
factoryplanner
FactorySearch
far-reach
Fill4Me
Flare Stack
flib
Flow Control
FNEI
grappling-gun
Gun_Turret_Alerts
IndustrialDisplayPlates
informatron
Insectitron
jetpack
Krastorio2
Krastorio2-more-locomotives
Krastorio2Assets
lightArtillery
LogisticTrainNetwork
LtnManager
LTN_Combinator_Modernized
LTN_Content_Reader
miniloader
ModuleInserter
nixie-tubes
PickerAtheneum
PickerBlueprinter
PickerExtended
PickerInventoryTools
PipeVisualizer
pushbutton
RateCalculator
Repair_Turret
reverse-factory
robotarmy
robot_attrition
shield-projector
simhelper
some-luaconsole
space-exploration
space-exploration-graphics
space-exploration-graphics-2
space-exploration-graphics-3
space-exploration-graphics-4
space-exploration-graphics-5
space-exploration-hr-graphics
space-exploration-postprocess
SpidertronEnhancements
spidertrontiers
Spider_Control
Squeak Through
stdlib
Teleporters
textplates
Todo-List
underground-pipe-pack
Unit_Control
utility-combinators
VehicleSnap
visual-signals
walls-block-spitters
YARM
</details>


I extracted *all* of my mods I have downloaded (not just those that are currently enabled)

This is a list of all those that have a reference to `__DebugAdapter` in them anywhere.

```
./AutoTrash_5.3.13/control.lua:131:        if __DebugAdapter then
./AutoTrash_5.3.13/control.lua:570:                        if __DebugAdapter then
./AutoTrash_5.3.13/control.lua:571:                            __DebugAdapter.breakpoint()
./FluidicPower_0.8.4/control.lua:71:-- require('__debugadapter__/debugadapter.lua')
./FluidicPower_0.8.4/control.lua:72:-- __DebugAdapter.print(expr,alsoLookIn)\
./FNEI_0.4.1/core/Debug.lua:56:  __DebugAdapter.print(message)
./FNEI_0.4.1/core/Debug.lua:69:  if __DebugAdapter then
./FNEI_0.4.1/core/Debug.lua:76:  if __DebugAdapter then
./Krastorio2_1.2.25/compatibility-scripts/data-final-fixes/space-exploration/0.3.X/entities.lua:1:-- require('__debugadapter__/debugadapter.lua')
./LTN_Combinator_Modernized_1.0.10/lib/gui.lua:551:--       __DebugAdapter.print(e)
./PickerAtheneum_1.2.4/control.lua:23:        __DebugAdapter.breakpoint('Manual Breakpoint Triggered')
./PickerAtheneum_1.2.4/scenarios/testing/control.lua:4:__DebugAdapter.levelPath('PickerAtheneum', 'scenarios/testing/')
./PickerInventoryTools_1.1.13/prototypes/final/packing-tape.lua:57:__DebugAdapter.print('Created ' .. count .. ' moveable chests.')
./RecipeBook_3.4.3/control.lua:124:  if __DebugAdapter then
./RecipeBook_3.4.3/control.lua:125:    __DebugAdapter.print(obj)
./RecipeBook_3.4.3/control.lua:154:  if __DebugAdapter and (not e.parameter or #e.parameter == 0) then
./RecipeBook_3.4.3/control.lua:155:    __DebugAdapter.print(database)
./RecipeBook_3.4.3/scripts/gui/info/actions.lua:294:    if __DebugAdapter then
./RecipeBook_3.4.3/scripts/gui/info/actions.lua:295:      __DebugAdapter.print(obj_data)
./RecipeBook_3.4.3/scripts/gui/info/index.lua:520:            __DebugAdapter and tool_button(nil, "Print", nil, { gui = "info", id = id, action = "print_object" }) or {},
./simhelper_1.1.2/funccapture.lua:37:local step_ignore = __DebugAdapter
./simhelper_1.1.2/funccapture.lua:38:  and __DebugAdapter.stepIgnore
./simhelper_1.1.2/funccapture.lua:64:if __DebugAdapter then
./simhelper_1.1.2/funccapture.lua:65:  __DebugAdapter.defineGlobal("__simhelper_funccapture")
./stdlib_1.4.6/stdlib/event/event.lua:281:            __DebugAdapter.print('Attempt to deregister already non-registered listener from event: ' .. event_id)
./stdlib_1.4.6/stdlib/event/event.lua:284:        __DebugAdapter.print('Attempt to deregister already non-registered listener from event: ' .. event_id)
./stdlib_1.4.6/stdlib/event/event.lua:529:__DebugAdapter.stepIgnore(Event)
./stdlib_1.4.6/stdlib/utils/globals.lua:92:if _ENV.__DebugAdapter then
./stdlib_1.4.6/stdlib/utils/globals.lua:93:    if _ENV.__DebugAdapter.attach then
./stdlib_1.4.6/stdlib/utils/globals.lua:96:            local object_info = require('__debugadapter__/luaobjectinfo.lua')
./stdlib_1.4.6/stdlib/utils/globals.lua:102:    _ENV.__DebugAdapter = {
./ZRecipeRandomizer_1.5.10/data-final-fixes.lua:1:-- require('__debugadapter__/debugadapter.lua')
```


Looking at the list the only time I see any mod "assigning" __DebugAdapter is stdlib...Time to disable that real quick and see what happens.

**Comment by justarandomgeek** [comment]
I've mentioned it to Nexela so hopefully a stdlib fix is coming soon!

**Comment by credomane** [comment]
Disabling stdlib did "fix" it but it also disabled about 6-8 other mods too. I then disabled the mods that needed stdlib then re-enabled it...still works. Slowly enabling the stdlib dependent mods and see which one in particular breaks things again.

**Comment by justarandomgeek** [comment]
yeah the more reasonable workaround for now will be to simply backlevel nixies and simhelper to the previous version

**Comment by credomane** [comment]
Minimal list of mods to trigger the error:

nixie-tubes
PickerAtheneum
PickerExtended  <--Disabling this mod let's the game load without issue.
simhelper
stdlib


If I load up the game with all the mods enabled in my original list but leave PickerExtended disabled everything works. Enable PickerExtended I get the original error that blames nixie-tubes again.

**Comment by justarandomgeek** [comment]
I've just pushed an update to check for the function also, for now.

**Comment by credomane** [comment]
lol. Now it just broke elsewhere. 
![image](https://user-images.githubusercontent.com/1283031/171913388-341abf46-be10-4d2c-b444-c7e2605a2835.png)


I'm not even sure I *use* PickerExtended anymore. So I'm just gonna disable it for now.

**Comment by justarandomgeek** [comment]
bleh. stdlib's fake stepIgnore doesn't return the argument...

**Comment by justarandomgeek** [comment]
Okay, i actually *tested* my fix this time!
